### ISSUE TITLE
Move https://github.com/inuits/hazelcast_exporter/

### ISSUE THREAD

**Issue by roidelapluie** [prometheus-community/community#11]
I would like to move https://github.com/inuits/hazelcast_exporter/ to this community.

**Comment by frittentheke** [comment]
@roidelapluie is a dedicated exporter even required to extract metrics from Hazelcast?

Hazelcast has built-in support for Prometheus (https://docs.hazelcast.com/hazelcast/latest/maintain-cluster/monitoring.html#prometheus) and one could also use the JMX exporter to collect the metrics.

**Comment by SuperQ** [comment]
Looks like we don't need this exporter with built-in metrics.
