### ISSUE TITLE
Adopt wmi_exporter

### ISSUE THREAD

**Issue by carlpett** [prometheus-community/community#13]
The maintainers of [wmi_exporter](https://github.com/martinlindhe/wmi_exporter) (me and @martinlindhe) would like to propose adopting the wmi_exporter into prometheus-community.

At the same time, the project also should be renamed, to reflect that we are now not only using WMI as a datasource. Proposed new name is simply "windows_exporter", but open for suggestions.

**Comment by SuperQ** [comment]
When should we do the transfer of the exporter to this group? Also, I recall there was an idea to rename this to `windows_exporter`, since the scope has expanded beyond just being a bridge to WMI.

**Comment by carlpett** [comment]
From my understanding there is still some unclarity on how prometheus-community would work? We haven't closed the discussions in #7 #8 #9, at least, which I had assumed was required before starting transfers?

**Comment by SuperQ** [comment]
We had a discussion at one of the previous developer summits and decided that it was OK to continue running the project under the existing Prometheus governance rules. Basically we need a volunteer from Prometheus Team to "sponsor" a project, but additional maintainers can be granted using our lazy consensus procedure.

Additional documentation is meant to expand things beyond those rules, but there's nothing stopping us from moving forward.

**Comment by SuperQ** [comment]
Ping @carlpett, we're now moving projects over if you're still interested in doing this. I can create a new management team under the prometheus-community org, and you can continue to be a maintainer and invite others to be maintainers.

We just need to select a Prometheus maintainer as the "steward". @brian-brazil or @RichiH, do either of you want to take this one?

**Comment by carlpett** [comment]
Yes, I think it would be very good to move it over! I actually opened an RFC issue in the exporter repo just this morning, so I hope we can get some input there on both the name but also what interesting dependencies have built up over the years on the specific name/url.
I think the rename+move combination has a potential to be a bit confusing if we don't do it in more or less one operation. Github generates redirects when a repo is renamed or moved, but if we stop in either intermediate stage (moved but not renamed or vice versa) we'll have to go through whatever pains twice, which seems unnecessary.

Thoughts? I can check with Github if they could help do a rename+transfer in a single operation.

**Comment by SuperQ** [comment]
I'm not sure you can rename and move in the same step.

**Comment by SuperQ** [comment]
wmi_exporter is now moved, now called windows_exporter.
