### ISSUE TITLE
adopt bind

### ISSUE THREAD

**Issue by anarcat** [prometheus-community/community#15]
hi!

the [bind exporter](https://github.com/digitalocean/bind_exporter/) is in fairly good shape in terms of contributions, but upstream seems to be struggling with issuing proper releases (see https://github.com/digitalocean/bind_exporter/issues/55). it seems @digitalocean is not really supporting it, so maybe it could be moved here.

**Comment by rayram23** [comment]
Hi All, Im an employee at DO and we are ready to move the repo over. Once someone gives me an `ack` we can move the repo over.

**Comment by anarcat** [comment]
i am not sure what the next step is here... "`ack`"? :)

**Comment by rayram23** [comment]
Lol. Thanks ill move the repo over now :)

**Comment by rayram23** [comment]
ah i got this error when trying to transfer:

`You don’t have the permission to create public repositories on prometheus-community`

**Comment by SuperQ** [comment]
@rayram23 Would it be an option to grant me access to the bind_exporter repo?

**Comment by SuperQ** [comment]
Ok, I've created a new team and permission setup to allow moving the exporter repo into the project.

**Comment by rayram23** [comment]
Sooooo... github said i could only transfer it between myself and an org.. So i transferred it to myself and now transferring it to “Prometheus-community” says i do not have permissions to create public repos in that org.

**Comment by rayram23** [comment]
<img width="1194" alt="Screenshot 2020-01-03 at 7 47 59 PM" src="https://user-images.githubusercontent.com/2936797/71757252-4c4cdd80-2e62-11ea-9344-c2361261e008.png">

**Comment by SuperQ** [comment]
@rayram23 GitHub says you haven't accepted the invite to the team. Check your notifications.

**Comment by rayram23** [comment]
Success!!! Moved over!

**Comment by anarcat** [comment]
awesome, thanks, so I guess this can be closed now! :)

**Comment by SuperQ** [comment]
Great, to kick off some maintenance, I've created a PR to update the build with the latest Prometheus templates/style.

https://github.com/prometheus-community/bind_exporter/pull/57
