### ISSUE TITLE
Move CodeMirror editor PromQL support to Prometheus Community

### ISSUE THREAD

**Issue by juliusv** [prometheus-community/community#20]
Similar to https://github.com/prometheus-community/community/issues/19, @Nexucis built PromQL support for the CodeMirror editor (which might be a candidate for usage in Prometheus itself potentially), and we are interested in transferring this repo to prometheus-community. This one doesn't have to be a fork, but can be a direct repo transfer.

@RichiH @SuperQ should we just do this or does there need to be a discussion?

**Comment by juliusv** [comment]
Forgot to include the link to the repo: https://github.com/Nexucis/codemirror-mode-promql

**Comment by SuperQ** [comment]
LGTM

**Comment by Nexucis** [comment]
Super news ! How do we proceed ? :)

**Comment by Nexucis** [comment]
Project has been transfered in the prometheus-community: https://github.com/prometheus-community/codemirror-promql

Thanks a lot @juliusv and @SuperQ for your help!
