### ISSUE TITLE
Add kitefactory

### ISSUE THREAD

**Issue by SuperQ** [prometheus-community/community#23]
The kitefactory project is used to automate the build of BuildKite agent nodes for the node_exporter's non-Linux/non-x86 build pipelines.

https://github.com/derekmarcotte/kitefactory

@derekmarcotte would like to bring this into the community so we can collaborate on maintaining the node_exporter builds.

CC @paulfantom, who might be interested in collaborating on some more Ansible. :grin:

**Comment by roidelapluie** [comment]
:+1:

**Comment by SuperQ** [comment]
This is completed.
