### ISSUE TITLE
Add elasticsearch_exporter to prometheus-community

### ISSUE THREAD

**Issue by roidelapluie** [prometheus-community/community#24]
https://github.com/justwatchcom/elasticsearch_exporter/issues/349

**Comment by rtkgjacobs** [comment]
Hello. Any movement on this?  What is the next step? Would love to see this project progress, we have contributions we'd like to make but the linked repo seems to have gone silent.

**Comment by simonfrey** [comment]
@roidelapluie  To be right: Is it enough if I transfer the ownership and then you can take over? 
![DeepinScreenshot_Navigator_20210528181830](https://user-images.githubusercontent.com/24354822/120013580-343ea680-bfe1-11eb-9433-2a7ba557563a.png)

cc. @metalmatze

**Comment by roidelapluie** [comment]
Yes

**Comment by metalmatze** [comment]
Yup, looks good. Go for it @simonfrey :+1: :rocket:

**Comment by simonfrey** [comment]
Done. https://github.com/orgs/prometheus-community/teams/elasticsearch_exporter/repositories

**Comment by metalmatze** [comment]
I think this is done now :)
