### ISSUE TITLE
Add prom-label-proxy to prometheus-community

### ISSUE THREAD

**Issue by brancz** [prometheus-community/community#25]
We would like to move/donate the prom-label-proxy project we have created originally to build light tenancy/isolation mechanisms in OpenShift for Prometheus and Alertmanager APIs. This component is entirely independent from OpenShift though, and there have been various mailing list threads with people interested in mechanisms like this, so we would love to make this available for more people.

@s-urbaniak @lilic @paulfantom @pgier @simonpasquier and myself are happy to continue to be maintainers for the project.

@simonpasquier and I are obviously happy to sponsor this, but don't want to just push this through within our group, so we'd love to hear other people's opinions as well :) 

https://github.com/openshift/prom-label-proxy

**Comment by SuperQ** [comment]
Seems like something useful to the wider community.

**Comment by bwplotka** [comment]
Awesome, I would say +10, just I would ensure a solid Auth API for this. I remember that's some requirement to use it, right?

**Comment by brancz** [comment]
The readme says it all I think. It explicitly does not take care of auth, it’s just a proxy to enforce arbitrary labels in requests/queries. It’s a building block.

**Comment by bwplotka** [comment]
ahh sorry for my ignorance, I keep asking same question. What I am missing in README is how to control the "enforcing" - some mention about this would be nice.

But anyways, feel free to move project and we can iterate, LGTM (:

**Comment by brancz** [comment]
Repo has been moved. Thanks everyone!
