### ISSUE TITLE
Add dswarbrick to node-exporter-textfile-collector-scripts

### ISSUE THREAD

**Issue by SuperQ** [prometheus-community/community#30]
I'd like to invite @dswarbrick as a maintainer of node-exporter-textfile-collector-scripts. They have done a number of good contributions and reviews of the various scripts.

**Comment by roidelapluie** [comment]
Awesome! :+1:

**Comment by roidelapluie** [comment]
Can this be closed?

**Comment by SuperQ** [comment]
Yes! This is done.
