### ISSUE TITLE
Adopt postgres_exporter

### ISSUE THREAD

**Issue by SuperQ** [prometheus-community/community#32]
Let's adopt the postgres_exporter.

* [x] Add maintainer team to GitHub.
* [x] Add @wrouesnel to team
* [x] Transfer project
* [x] :tada: 

See: https://github.com/wrouesnel/postgres_exporter/issues/475

**Comment by wrouesnel** [comment]
Project transferred! Feels good to have it in a shared home. The immediate effect of this is going to be that the `wrouesnel/postgres_exporter:latest` docker image starts aging though since this (should) break the travis permissions.

**Comment by SuperQ** [comment]
Nice, thanks! I have some time on Friday I could work on getting the cleanup done on the project for project path, docs, CI, etc.
