### ISSUE TITLE
An ECS exporter

### ISSUE THREAD

**Issue by rakyll** [prometheus-community/community#36]
I have written a lightweight ECS exporter that is positioned to run as a sidecar container on tasks to publish ECS infrastructure metrics in the Prometheus format. There is substantial interest from the [community](https://twitter.com/rakyll/status/1433222532950159363) and the existing customers to be able to export ECS metrics in the Prometheus exposition format. 

I would like to open source the sidecar and maintain it on behalf of the ECS team and wondering if this organization is a better place for it. I'd like to kick of the process to contribute to here if there is any interest. Complimented by the discovery contributions (https://github.com/prometheus/prometheus/issues/9310), the ECS exporter will make it easier for ECS users to adopt Prometheus.

**Comment by roidelapluie** [comment]
Hello, it looks fine to me, there are a couple of things to note:

In this organisation, we follow the CNCF COC, we prefer Apache 2.0 and we also use the Prometheus build+release toolchain. We can help with that of course (we frequently migrate other build systems to the Prometheus one), so you do not really need to care about that.

You and your team get maintainer access to the repository.

cc @SuperQ

**Comment by rakyll** [comment]
Thanks much. It uses Apache 2.0. I will add the required files for CNCF COC. I will take a look at the Prometheus toolchain and switch to it and continue the process to open source it.

**Comment by roidelapluie** [comment]
The COC and toolchain would be sync automatically ( https://github.com/prometheus/prometheus/blob/0111aa987e600c861dff34e4d24e891ed63d0535/scripts/sync_repo_files.sh#L40 ). Here's an example of migration: https://github.com/prometheus-community/postgres_exporter/pull/480

**Comment by roidelapluie** [comment]
Note: before creating the repository and the team, I will let other team members voice their opinion on this.

**Comment by SuperQ** [comment]
Sounds like a good idea to me.

**Comment by RichiH** [comment]
Disclaimer: I suggested this GH org to @rakyll 

LGTM.

CC @matthiasr for overlap with https://github.com/prometheus/cloudwatch_exporter

**Comment by rakyll** [comment]
Thanks much, got the invite!

**Comment by matthiasr** [comment]
I am glad that this is happening! I think it's great that Prometheus users can get at this data without looping through CloudWatch with the associated impedance mismatch. There will still be a need for a CloudWatch exporter for other AWS services (for now?) but that is a separate discussion.

**Comment by rakyll** [comment]
What's the next step? Do you want to review the import? I switched to the Prometheus toolchain and added the missing files and am ready to publish it.

**Comment by RichiH** [comment]
Go ahead and populate; there's more than enough trust to know that you'll follow through on reviews and updates.

If you would prefer to move an existing repo over, just let us know, else https://github.com/prometheus-community/ecs_exporter is at the ready. Do you need additional users on https://github.com/orgs/prometheus-community/teams/ecs_exporter ?

**Comment by roidelapluie** [comment]
I have created a LICENSE so you can make a pull request.
