### ISSUE TITLE
Import github.com/soundcloud/ipmi_exporter

### ISSUE THREAD

**Issue by bitfehler** [prometheus-community/community#38]
Hi there,

I'd like to get the ball rolling on moving the [IPMI exporter](https://github.com/soundcloud/ipmi_exporter) into this org. I would like to continue maintaining it, the main purpose would be to consolidate the setup for CI builds and Docker images, which we cannot do in our current org (see https://github.com/soundcloud/ipmi_exporter/issues/70).

@SuperQ has some access to that repo already, but might not be sufficient for the move. I'll take a closer look at our options there. Maybe @matthiasr might also be able to help out here?

**Comment by matthiasr** [comment]
I think this is a good idea! We can work out the process when I am back at
work?

**Comment by SuperQ** [comment]
Sounds good, I will start by setting up the GitHub group.

**Comment by bitfehler** [comment]
https://github.com/prometheus-community/ipmi_exporter
Thanks!
