### ISSUE TITLE
[Proposal] Adopt FreshTracks github repos

### ISSUE THREAD

**Issue by igaskin** [prometheus-community/community#39]
Up until 2018 Freshtracks.io, was pioneering analytics and performance tooling built on top of prometheus.  After Freshtracks [shut down](https://blog.freshtracks.io/swan-song-96ce02ef854f) in November 2018, the collection of prometheus related tools hosted within its repository were left without owners; https://github.com/open-fresh.

This is a proposal to fork or move the four public repos that belonged to FreshTracks, and move them under the prometheus github organization.  It is my belief that these repos still continue to serve the prometheus community, as shown by the issues and PRs that continue to be raised in repos without maintainers.

**Comment by SuperQ** [comment]
Sure, I could see some of those repos being something we could adopt if there are community maintainers willing to take over updating them.

**Comment by igaskin** [comment]
I can help maintain https://github.com/open-fresh/avalanche.

**Comment by roidelapluie** [comment]
I have invited you so you can transfer the repository :)

**Comment by igaskin** [comment]
Cool, just accepted the invite.  I should clarify that I am a member of the community, I am not associated with Freshtracks in any way.   I can transfer my fork of the repository, but cannot transfer the original since I am not a member of the open-fresh organization.

My understanding is that some of the Freshtracks members ended up at Grafana/Prometheus.  If they are still around, maybe they can transfer the original? Otherwise I'm happy to transfer my fork.

**Comment by csmarchbanks** [comment]
Hello, I am that member of FreshTracks who is now at Prometheus/Grafana :), I haven't had time to maintain avalanche recently and do not personally use it much anymore so I am happy to transfer it and have a new maintainer! Before doing so I would like buy in from a couple of other FreshTracks people, especially how they want to handle it (move the repo, archive it, etc...).

cc: @limscoder @mchipouras

**Comment by mchipouras** [comment]
I am very supportive of transferring all 4 repos over to Prometheus community. It would be great to have some new energy pushing these projects forward

**Comment by mchipouras** [comment]
success.  https://github.com/prometheus-community/avalanche
