### ISSUE TITLE
add @dongjiang1989 to team @prometheus-community/community

### ISSUE THREAD

**Issue by dongjiang1989** [prometheus-community/community#49]
add @dongjiang1989 to team @prometheus-community/community

See: 
1. @dongjiang1989 is maintainer.  like: https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-pingmesh-exporter
2. @dongjiang1989 is contributor.   like: https://github.com/prometheus-community/helm-charts/pull/3337 https://github.com/prometheus-operator/prometheus-operator/pull/5449

**Comment by SuperQ** [comment]
Verified, invite sent.

**Comment by dongjiang1989** [comment]
@SuperQ  Thinks for Invite.
