### ISSUE TITLE
Adopt the unifi_exporter

### ISSUE THREAD

**Issue by SuperQ** [prometheus-community/community#5]
The [unifi_exporter](https://github.com/mdlayher/unifi_exporter) seems to be the only reasonable Prometheus exporter for Ubiquiti Unifi.

I would like to see development continue, as I use Ubiquiti stuff in a couple places.

@mdlayher Do you think it would be useful to bring your code into the Prometheus Community projet to see if we can get some new contributors?

I am happy to sponsor adoption of this exporter.

**Comment by mdlayher** [comment]
If you'd like to do that, you're more than welcome to. I've stopped running it in favor of the SNMP exporter as that gives me basically all the info I need anyway.

**Comment by SuperQ** [comment]
The Unifi Poller (now UnPoller) now has good Prometheus support. There's no need for this.

https://unpoller.com/
