### ISSUE TITLE
Adopt jiralert

### ISSUE THREAD

**Issue by bwplotka** [prometheus-community/community#6]
I would like to propose moving https://github.com/free/jiralert to prometheus-community. It is a quite alert manager webhook created by @free that creates tickets from alerts.

Happy to sponsor it as well, despite that, we currently don't use it in my new job (: Still, I think it would be awesome to have it here in community space. 

@free are you happy with this? I think we initially discussed this offline couple of months ago.

**Comment by free** [comment]
SGTM :+1:

**Comment by simonpasquier** [comment]
Done, for reference [discussion](https://groups.google.com/d/msg/prometheus-developers/4GyuB_1QfCA/Cj0QVLciBAAJ) on the prometheus-dev list.
